---
abstract: 'Samurai de gozaru'
author:
  - 'Naoki Tomita <tomita@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.11
  Test::Base: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-Samurai
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  Class::Trigger: 0
  Encode: 0
  File::ShareDir: 0
  Lingua::JA::Alphabet::Yomi: 0
  Lingua::JA::Numbers: 0
  Text::MeCab: 0
  Unicode::Japanese: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
